version: 2
updates:
- package-ecosystem: gradle
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: org.flywaydb.flyway
    versions:
    - 7.5.4
    - 7.6.0
    - 7.7.0
    - 7.7.1
    - 7.7.2
    - 7.7.3
    - 7.8.0
    - 7.8.1
  - dependency-name: org.springframework.cloud:spring-cloud-starter-netflix-hystrix
    versions:
    - 2.2.6.RELEASE
    - 2.2.7.RELEASE
  - dependency-name: org.postgresql:postgresql
    versions:
    - 42.2.18
    - 42.2.19
  - dependency-name: org.springframework.boot
    versions:
    - 2.4.2
    - 2.4.3
    - 2.4.4
  - dependency-name: org.springframework.cloud:spring-cloud-starter-openfeign
    versions:
    - 3.0.1
  - dependency-name: org.projectlombok:lombok
    versions:
    - 1.18.18
  - dependency-name: io.freefair.lombok
    versions:
    - 5.3.0
  - dependency-name: com.github.ben-manes.versions
    versions:
    - 0.36.0
  - dependency-name: org.apache.tomcat.embed:tomcat-embed-core
    versions:
    - 10.0.0
    - 10.0.2
  - dependency-name: org.owasp.dependencycheck
    versions:
    - 6.1.0
  - dependency-name: net.serenity-bdd:serenity-gradle-plugin
    versions:
    - 2.3.12
