server:
  port: 8099

management:
  health:
    probes:
      enabled: true
  endpoint:
    health:
      show-details: "always"
  endpoints:
    web:
      base-path: /
      exposure:
        include: health, info, prometheus

enableSwagger: ${ENABLE_SWAGGER:true}

config:
  stacktraceEnabled:  ${STACKTRACE_ENABLED:false}

camunda:
  url: ${CAMUNDA_URL:http://localhost:8080/engine-rest}
  getTaskDmnId: getTask

govUkHolidays:
  url: https://www.gov.uk/

#logging:
#  level:
#    org.springframework: debug

#If you use a database then uncomment below lines and update db properties accordingly
spring:
  application:
    name: wa-workflow-api
  main:
   allow-bean-definition-overriding: true

security:
  anonymousPaths:
    - "/"
    - "/health"
    - "/health/liveness"
    - "/loggers/**"
    - "/swagger-ui.html"
    - "/swagger-resources/**"
    - "/v2/api-docs"
    - "/webjars/springfox-swagger-ui/**"
    - "/favicon.ico"
  authorisedServices:
    - "wa_task_configuration_api"
    - "wa_task_management_api"

auth:
  idam:
    client:
      baseUrl: ${IDAM_URL:http://sidam-api}
      detailsUri: "/details"
      id: ${WA_IDAM_CLIENT_ID:wa}
      secret: ${WA_IDAM_SECRET:something}
      redirectUri: ${WA_IDAM_REDIRECT_URI:http://localhost}
  provider:
    service:
      client:
        baseUrl: ${S2S_URL:http://service-auth-provider-api}

idam:
  s2s-auth:
    url: ${S2S_URL:http://service-auth-provider-api}
    secret: ${S2S_SECRET_WORKFLOW:AAAAAAAAAAAAAAAC}
    name: ${WA_S2S_NAME:wa_workflow_api}
