logging:
  level:
    org.springframework: info
    org.springframework.transaction: debug
    uk.gov.hmcts.reform: debug

feign:
  client:
    config:
      default:
        loggerLevel: full

spring.jackson.serialization.indent_output: true

security:
  authorisedServices:
    - "wa_workflow_api"
    - "wa_case_event_handler"
    - "camunda-local-bpm"
