server:
  port: 8099

management:
  health:
    probes:
      enabled: true
  endpoint:
    health:
      show-details: "always"
  endpoints:
    web:
      base-path: /
      exposure:
        include: health, info, prometheus

config:
  enableSwagger: ${ENABLE_SWAGGER:true}

camunda:
  url: ${CAMUNDA_URL:http://camunda-bpm/engine-rest}
  getTaskDmnId: getTask

task-management-api:
  url: ${TASK_MANAGEMENT_URL:http://localhost:8087}

govUkHolidays:
  url: https://www.gov.uk/

spring:
  config:
    import: "optional:configtree:/mnt/secrets/wa/"
  data.rest.basePath: /testing
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    properties:
      hibernate:
        show_sql: true
        default_schema: ${POSTGRES_NAME:wa_workflow_api}
  application:
    name: WA workflow api
  main:
    allow-bean-definition-overriding: true
  datasource:
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://${POSTGRES_HOST:localhost}:${POSTGRES_PORT:5432}/${POSTGRES_NAME:wa_workflow_api}${POSTGRES_CONNECTION_OPTIONS:}
    username: ${POSTGRES_USERNAME:postgres}
    password: ${POSTGRES_PASSWORD:}
    properties:
      charSet: UTF-8
  flyway:
    enabled: true
    baselineOnMigrate: true
    schemas: ${POSTGRES_NAME:wa_workflow_api}
security:
  anonymousPaths:
    - "/"
    - "/health"
    - "/health/liveness"
    - "/health/readiness"
    - "/loggers/**"
    - "/swagger-resources/**"
    - "/swagger-ui/**"
    - "/swagger-ui/index.html"
    - "/v3/**"
    - "/favicon.ico"

auth:
  provider:
    service:
      client:
        baseUrl: ${S2S_URL:http://service-auth-provider-api}

idam:
  s2s-auth:
    url: ${S2S_URL:http://service-auth-provider-api}
    secret: ${S2S_SECRET_WORKFLOW_API:AAAAAAAAAAAAAAAC}
    name: wa_workflow_api
  s2s-authorised:
    services: ${WA_S2S_AUTHORIZED_SERVICES:wa_workflow_api,wa_case_event_handler,camunda-bpm,xui_webapp,wa_task_management_api}

launchDarkly:
  sdkKey: ${LAUNCH_DARKLY_SDK_KEY:sdk-key}
  connectionTimeout: 5000
  socketTimeout: 5000

logging:
  level:
    root: INFO
    org.zalando.logbook: TRACE

feign:
  client:
    config:
      default:
        loggerLevel: basic

logbook:
  include: /workflow/**

