server:
  port: 8099

management:
  health:
    probes:
      enabled: true
  endpoint:
    health:
      show-details: "always"
  endpoints:
    web:
      base-path: /
      exposure:
        include: health, info, prometheus

enableSwagger: ${ENABLE_SWAGGER:true}

config:

camunda:
  url: ${CAMUNDA_URL:http://camunda-local-bpm/engine-rest}
  getTaskDmnId: getTask

govUkHolidays:
  url: https://www.gov.uk/

spring:
  jpa.properties.hibernate:
    show_sql: true
    default_schema: ${POSTGRES_NAME:wa_workflow_api}
  application:
    name: WA workflow api
  main:
   allow-bean-definition-overriding: true
  datasource:
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://${POSTGRES_HOST:localhost}:${POSTGRES_PORT:5432}/${POSTGRES_NAME:wa_workflow_api}${POSTGRES_CONNECTION_OPTIONS:}
    username: ccd
    password: ccd
    properties:
      charSet: UTF-8
  flyway:
    enabled: true
    baselineOnMigrate: true
    schemas: ${POSTGRES_NAME:wa_workflow_api}
security:
  anonymousPaths:
    - "/"
    - "/health"
    - "/health/liveness"
    - "/health/readiness"
    - "/loggers/**"
    - "/swagger-ui.html"
    - "/swagger-resources/**"
    - "/v2/api-docs"
    - "/webjars/springfox-swagger-ui/**"
    - "/favicon.ico"
  authorisedServices:
    - "wa_workflow_api"
    - "wa_case_event_handler"
    - "camunda-local-bpm"

auth:
  provider:
    service:
      client:
        baseUrl: ${S2S_URL:http://service-auth-provider-api}

idam:
  s2s-auth:
    url: ${S2S_URL:http://service-auth-provider-api}
    secret: ${S2S_SECRET_WORKFLOW_API:AAAAAAAAAAAAAAAC}
    name: ${S2S_NAME_WORKFLOW_API:wa_workflow_api}

credentials:
  wa:
    system:
      user: ${WA_SYSTEM_USERNAME:system-user}
      password: ${WA_SYSTEM_PASSWORD:system-password}
