apiVersion: v2
appVersion: "1.0"
description: A Helm chart for wa-workflow-api App
name: wa-workflow-api
home: https://github.com/hmcts/wa-workflow-api
version: 0.0.16
maintainers:
  - name: HMCTS wa team
dependencies:
  - name: java
    version: 3.4.5
    repository: '@hmctspublic'
