java:
  applicationPort: 8099
  image: 'hmctspublic.azurecr.io/wa/workflow-api:latest'
  ingressHost: wa-workflow-api-{{ .Values.global.environment }}.service.core-compute-{{ .Values.global.environment }}.internal
  aadIdentityName: wa
  environment:
    RESTART_APP: 1
    ENABLE_SWAGGER: true
    CAMUNDA_URL: "http://camunda-api-{{ .Values.global.environment }}.service.core-compute-{{ .Values.global.environment }}.internal/engine-rest"
    S2S_URL: "http://rpe-service-auth-provider-{{ .Values.global.environment }}.service.core-compute-{{ .Values.global.environment }}.internal"
    POSTGRES_PORT: 5432
    POSTGRES_HOST: wa-workflow-api-postgres-db-{{ .Values.global.environment }}.postgres.database.azure.com
    POSTGRES_NAME: wa_workflow_api
    POSTGRES_CONNECTION_OPTIONS: "?sslmode=require"
  keyVaults:
    wa:
      secrets:
        - AppInsightsInstrumentationKey
        - s2s-secret-workflow-api
        - workflow-api-POSTGRES-PASS
        - workflow-api-POSTGRES-USER
        - ld-secret
