java:
  image: ${IMAGE_NAME}
  ingressHost: ${SERVICE_FQDN}
  environment:
    RESTART_APP: 1
    CAMUNDA_URL: "http://{{ .Release.Name }}-camunda/engine-rest"
    S2S_URL: "http://rpe-service-auth-provider-{{ .Values.global.environment }}.service.core-compute-{{ .Values.global.environment }}.internal"
    POSTGRES_NAME: wa_workflow_api
    POSTGRES_HOST: '{{ .Values.global.postgresHost }}'
    POSTGRES_USERNAME: '{{ .Values.global.postgresUsername }}'
    POSTGRES_PASSWORD: '{{ .Values.global.postgresPassword }}'
    POSTGRES_CONNECTION_OPTIONS: ""
  keyVaults:
    wa:
      secrets:
        - name: AppInsightsInstrumentationKey
          alias: azure.application-insights.instrumentation-key
        - name: s2s-secret-workflow-api
          alias: S2S_SECRET_WORKFLOW_API
#  postgresql:
#    enabled: true
#    auth:
#      database: wa_workflow_api

wa:
  enabled: true
  wa:
    taskManagement:
      enabled: false
    taskMonitor:
      enabled: false
    eventHandler:
      enabled: false
    workflow:
      enabled: false
    taskBatchCron:
      enabled: false
    messageCron:
      enabled: false
    camunda:
      enabled: true
    postgresql:
      enabled: true
    servicebus:
      enabled: false
