logging:
  level:
    org.springframework:
      dao: debug
      transaction: debug
      jdbc.core.JdbcTemplate: debug
    org.hibernate:
      SQL: debug
      type.descriptor.sql.BasicBinder: trace
      engine: debug
    uk.gov.hmcts.reform: debug

feign:
  client:
    config:
      default:
        loggerLevel: full

spring.jackson.serialization.indent_output: true
