spring.flyway.enabled: false

spring:
  datasource:
    driverClassName: org.h2.Driver
    url: jdbc:h2:mem:wa_workflow_api;MODE=PostgreSQL
    username: sa
    password: password
    platform: h2
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      default_schema: ${POSTGRES_NAME:wa_workflow_api}
