spring.flyway.enabled: false

spring:
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    properties:
      hibernate:
        show_sql: true
        default_schema: ${POSTGRES_NAME:wa_workflow_api}
    hibernate.ddl-auto: create
