spring.flyway.enabled: false

spring:
  datasource:
    driverClassName: org.h2.Driver
    url: jdbc:h2:mem:wa_workflow_api
    username: sa
    password: password
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      default_schema: wa_workflow_api
